### ISSUE TITLE
output to multicast or pipe and then gumd

### ISSUE THREAD

**Issue by josepowera** [futzu/SuperKabuki#1]
After checking output parameters I only see file as output... 

Is multicast / pipe / pipe+gumd supported?

**Comment by futzu** [comment]
Hey man I am just seeing this, 
hmmm..... I just need to print to stderr , and add writing to stdout and then it will work.
Ill try to get to it today.
Good idea by the way.

**Comment by futzu** [comment]
now it will work
I set the default input to stdin 
 default out to stdout 
and print everything to stderr.

input  is 0
output is 1
printing to 2

**Comment by futzu** [comment]
Let me know how it works out for you.
