### ISSUE TITLE
Problem with using Superkabuki to insert time signal cues at every iframe.

### ISSUE THREAD

**Issue by Avencheng** [futzu/SuperKabuki#3]
Hi Adrian,
This might be a stupid question,
I'm trying to inject SCTE-35 in ts, but I have an issue with the command :
`superkabuki -i independent_frame_ts/0.ts -o output.ts -t`
but it returns the output: `scte35 pid must be set`
I only have the PTS for cue-out and cue-in, not PID. What steps am i missing?

**Comment by Avencheng** [comment]
I have added -p 0x86 in the command, and it worked, please correct me if i did it wrong:
`superkabuki -i independent_frame_ts/0.ts -o output.ts -t -p 0x86`

**But now i have another issue:**

the PTS of the last frame in output.ts is 315.200000(but it has AD video in the middle, from PTS 19.966667 to 275.96667), so i'm trying to insert cue-out at PTS 19.933334, since the PTS of last frame of the program video in the beginning is 19.933333; and also insert cue-in at PTS 275.96668, since the PTS of last frame of the AD video is 275.96667. 
My sidecar.txt looks like this:
```
(computer_vision) aven.cheng@tgcusers-MacBook-Pro from_Peiwei % cat sidecar.txt          
19.933334, /DAvAAAAAAAA///wFAVIAACPf+/+c2nALn4AUsz1AAAAAAAKAAhDVUVJAAABNRsa+PM=
275.96668, /DAvAAAAAAAA///wFAVIAACPf2/+c2nALn4AUsz1AAAAAAAKAAhDVUVJAAABNZnCyYU=
```
but when i running the command: `superkabuki -i output.ts -s sidecar.txt -p 0x86`
the garbled characters keep appearing in terminal, and never stop:
![33](https://github.com/futzu/SuperKabuki/assets/72959212/762721fc-8519-4d5a-8959-252010dfb4f0)

Any idea for what's going on? Any help will be appreciated.

**Comment by futzu** [comment]
You didn't give it an output, so it wrote to stdout, you can redirect it to file or give it an output file name.
`superkabuki -i output.ts -s sidecar.txt -p 0x86 > out.ts`

**Comment by Avencheng** [comment]
Thanks Adrian, problem solved!!
